<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageReference Include="Microsoft.OpenApi" Version="1.6.22" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApplicationService.Core.Application\ApplicationService.Core.Application.csproj" />
    <ProjectReference Include="..\ApplicationService.Infrastructure.Shared\ApplicationService.Infrastructure.Shared.csproj" />
    <ProjectReference Include="..\ApplicationService.Infrastructure.Persistence\ApplicationService.Infrastructure.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\IDN\" />
    <Folder Include="Controllers\KHM\" />
    <Folder Include="Controllers\PHL\" />
    <Folder Include="Docs\" />
  </ItemGroup>

</Project>
