<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ApplicationService.Core.Domain\ApplicationService.Core.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="AuthService\Features\Customer\Commands\" />
    <Folder Include="ValuableService\" />
    <Folder Include="QuotationService\" />
    <Folder Include="ProposalService\" />
    <Folder Include="ProfileService\" />
    <Folder Include="ProductService\" />
    <Folder Include="PolicyService\" />
    <Folder Include="PaymentService\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Azure.Core" Version="1.38.0" />
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
